### ISSUE TITLE
Icon Scaling

### ISSUE THREAD

**Issue by SpookyCongee** [Georodin/DDI-DeepDrill-Indicator#1]
Howdy, I just found your mod and its more or less exactly what I was looking for! Thank you for making it public. I was wondering if there is any way to have the icons match the behavior of vanilla, where the resource icons are a standard size when zoomed in, but get smaller as you zoom out? With Camera+ especially the icons get quite enormous when zoomed out. It would just be a visual nicety that I think would help get it to the first page! But again, I appreciate the functionality greatly, thanks.

**Comment by Georodin** [comment]
I added a IconSize slider in the mod options for you
plis tell me if it is sufficient, I may could add also the camera height as additional value to influence the size
but imo even with Camera+ this icons look fine too me

**Comment by SpookyCongee** [comment]
Thank you for the effort! The slider definitely helps, for me 18 is about right. Is there a way to dynamically scale the icons so they remain consistent with the tile size when zoomed in or zoomed out? (that'd just be a visual nicety, the functionality is there as is, it's really more of a question than a request!) The only other thought I had about the mod was whether it would be possible to add a menu option to select which resource is being displayed, primarily to disable seeing steel as it's often the most common one. Prior to finding your mod I'd setup areas for each kind of resource, a different colour for each one, adding new sections to the area as new resources are found. It works, but it's certainly not the most efficient system for deep drill resource management. (edit - terminology clarity)

**Comment by Georodin** [comment]
cool idea with the Steel
and yes but I dont know where the camera height is stored would have to ask that
maybe I push another update just today

**Comment by SpookyCongee** [comment]
Thank you. I'll happily take a look at any update whenever you get a chance to work on it, no rush.

**Comment by Georodin** [comment]
https://github.com/Georodin/DDI-DeepDrill-Indicator/releases/tag/1.4.1
Closed with this version
